version: '3'
services:
  database:
    image: postgres:alpine
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=S3rver*
      - POSTGRES_DB=spring_microservices
    volumes:
      - ./pg-data:/var/lib/postgresql/data/
      - ./server.crt:/var/lib/postgresql/server.crt
      - ./server.key:/var/lib/postgresql/server.key
  microservice:
    image: bairesdev.com/microservice-spring-security-jpa:0.0.1
    ports:
      - 9001:9001
    environment:
      - JAVA_OPTS=
      - DB_HOST=database
    depends_on:
      - "database"